/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AisRouteImport } from './routes/ais'
import { Route as BacktrackingRouteImport } from './routes/backtracking'
import { Route as SatelliteRouteImport } from './routes/satellite'
import { Route as SuspectsRouteImport } from './routes/suspects'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AisRoute = AisRouteImport.update({
  id: '/ais',
  path: '/ais',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktrackingRoute = BacktrackingRouteImport.update({
  id: '/backtracking',
  path: '/backtracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SatelliteRoute = SatelliteRouteImport.update({
  id: '/satellite',
  path: '/satellite',
  getParentRoute: () => rootRouteImport,
} as any)
const SuspectsRoute = SuspectsRouteImport.update({
  id: '/suspects',
  path: '/suspects',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ais': typeof AisRoute
  '/backtracking': typeof BacktrackingRoute
  '/satellite': typeof SatelliteRoute
  '/suspects': typeof SuspectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ais': typeof AisRoute
  '/backtracking': typeof BacktrackingRoute
  '/satellite': typeof SatelliteRoute
  '/suspects': typeof SuspectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ais': typeof AisRoute
  '/backtracking': typeof BacktrackingRoute
  '/satellite': typeof SatelliteRoute
  '/suspects': typeof SuspectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ais' | '/backtracking' | '/satellite' | '/suspects'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ais' | '/backtracking' | '/satellite' | '/suspects'
  id: '__root__' | '/' | '/ais' | '/backtracking' | '/satellite' | '/suspects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AisRoute: typeof AisRoute
  BacktrackingRoute: typeof BacktrackingRoute
  SatelliteRoute: typeof SatelliteRoute
  SuspectsRoute: typeof SuspectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ais': {
      id: '/ais'
      path: '/ais'
      fullPath: '/ais'
      preLoaderRoute: typeof AisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtracking': {
      id: '/backtracking'
      path: '/backtracking'
      fullPath: '/backtracking'
      preLoaderRoute: typeof BacktrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satellite': {
      id: '/satellite'
      path: '/satellite'
      fullPath: '/satellite'
      preLoaderRoute: typeof SatelliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suspects': {
      id: '/suspects'
      path: '/suspects'
      fullPath: '/suspects'
      preLoaderRoute: typeof SuspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AisRoute: AisRoute,
  BacktrackingRoute: BacktrackingRoute,
  SatelliteRoute: SatelliteRoute,
  SuspectsRoute: SuspectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
